### ISSUE TITLE
Could not find a task generator for the name 'ns3-visible-light-communication'

### ISSUE THREAD

**Issue by fr3man2** [Aldalbahias/VLC-ns3-v3.25#1]
Hi,
Previously i have tried you VLC framework and it worked, except that goodput part.
Now i have decided to try this 3.25 version and received this error:
andrius@DESKTOP-3UIF67A:~/workspace/ns-allinone-3.26/ns-3.26$ sudo ./waf build
Waf: Entering directory `/home/andrius/workspace/ns-allinone-3.26/ns-3.26/build'
Could not find a task generator for the name 'ns3-visible-light-communication'

Could you help me you on sorting what could be causing it ?
Thanks

**Comment by fr3man2** [comment]
Solution was simple, just put module source in src/vlc and nothing else. very obvious.

**Comment by niazsakib** [comment]
Hi I am having the same error. The solution you have mentioned, I actually can't figure it out. Would you elaborate it. Thanks in advance.
